# -*- coding: utf-8 -*-
"""Copia de FastAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17o_BV7BWwEj98Va5F75OIuk3xZscbdBL
"""

pip install fastapi scikit-learn uvicorn

pip install ucimlrepo

pip install app

import pandas as pd
from ucimlrepo import fetch_ucirepo
import sys

class DataIngest():
    @staticmethod
    def data_ingest():
        """
        Perform data ingestion from remote source.
        """
        # 162 for forest fires
        dataset_ = fetch_ucirepo(id=162)
        X = dataset_.data.features
        y = dataset_.data.targets
        return pd.concat([X, y], axis = 1)

if __name__ == '__main__':
    output_file = sys.argv[1]
    data = DataIngest.data_ingest()
    data.to_csv(output_file, index=False)

# main.py
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List
import pickle
import numpy as np

# Load the model
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Load the target names (class labels)
data = DataIngest()
target_names = data.data_ingest

# Define the input data format for prediction
class ForestFire(BaseModel):
    features: List[float]

# Initialize FastAPI
app = FastAPI()

# Prediction endpoint
@app.post("/predict")
def predict(ff_data: ForestFire):
    if len(ff_data.features) != model.n_features_in_:
        raise HTTPException(
            status_code=400,
            detail=f"Input must contain {model.n_features_in_} features."
        )
    # Predict
    prediction = model.predict([ff_data.features])[0]
    prediction_name = target_names[prediction]
    return {"prediction": int(prediction), "prediction_name": prediction_name}

# Root endpoint
@app.get("/")
def read_root():
    return {"message": "Fire Forest model API"}

!uvicorn main:app --host 127.0.0.1 --port 8000

$headers = @{
    "Content-Type" = "application/json"
}

$body = @{
    "features" = @(13.2, 2.7, 2.36, 21, 100, 2.98, 3.15, 0.22, 2.26, 6.5, 1.05, 3.33, 820)
} | ConvertTo-Json

Invoke-RestMethod -Uri "http://localhost:8000/predict" -Method Post -Headers $headers -Body $body

# Dockerfile
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy files to container
COPY model.pkl /app/
COPY main.py /app/

# Install dependencies
RUN pip install fastapi uvicorn scikit-learn pydantic

# Expose port
EXPOSE 8000

# Start the FastAPI server
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]

# Build the Docker image
docker build -t fireforest-classification-api

# Run the Docker container
docker run -p 8000:8000 fireforest-classification-api