FROM python:3.9-slim
WORKDIR /app
COPY final_model.pkl /app/
COPY main.py /app/
RUN pip install fastapi uvicorn scikit-learn pydantic
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]